---
logging:
  level: INFO
  loggers:
    vasanti: DEBUG

database:
  # the name of your JDBC driver
  driverClass: com.mysql.cj.jdbc.Driver

  # the username
  user: root

  # the password
  password: kiran

  # the JDBC URL; make sure to use the correct port and database name
  url: jdbc:mysql://localhost:3306/badi1991_listngrow?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when checking a connection's validity
  validationQuery: "SELECT 1"

  # the minimum number of connections to keep open
  minSize: 5

  # the maximum number of connections to keep open
  maxSize: 25

  # whether idle connections should be validated
  checkConnectionWhileIdle: false

  # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
  evictionInterval: 10s

  # the minimum amount of time an connection must sit idle in the pool before it is eligible for eviction
  minIdleTime: 1 minute

  # the maximum amount of time a connection can be open, whether in use or idle
  maxConnectionAge: 1h

  # the frequency with which to validate idle connections
  validationInterval: 15s


